name: random-journals

on:
  push:
    branches:
      - main

jobs:
  deploy:
    env:
      AWS_EXPORTS: ${{ secrets.EXPORTS }}
      AWS_PROFILE: ${{ secrets.AWS_PROFILE}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Populate aws-exports
        run: |
          echo $AWS_EXPORTS > src/aws-exports.js

      - name: Build
        run: npm run build

      - name: Configure aws
        run: |
          echo $AWS_PROFILE >> ~/.aws/credentials

      - name: Install amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Configure Amplify
        run: |
          amplify init --amplify "{\"envName\":\"prod\"}" --providers "{\"awscloudformation\": {\"useProfile\":true, \"profileName\":\"rj-amplify\"}}" --yes

      - name: Deploy to production
        run: amplify publish --invalidateCloudFront --yes
